name: test_env
dependencies:
  - python=3.7
  - conda-forge::bilby
  - jupyter
  - conda-forge::ptemcee
  - seaborn
  - conda-forge::sphinx_rtd_theme
  - conda-forge::sphinxcontrib-bibtex
  - conda-forge::nbsphinx
  - conda-forge::pandoc
