name: Sphinx docs to gh-pages
env:
  CLONE_PATH: ${{ github.workspace }}
  HTML_DOCS:  ${{ github.workspace }}/docs/build_html
on:
  pull_request:
    branches:
      - develop
#  push:
#    branches:
#      - main

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  sphinx_docs_to_gh-pages:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install pandoc
      - name: Setup base Python environment
        run: |
          $CLONE_PATH/.github/workflows/setup_base_python.sh ${{ runner.os }}
      - name: Build Sphinx documentation
        run: |
          pushd $CLONE_PATH
          tox -r -e html
          popd
      - name: Archive HTML-format docs
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: ${{ env.HTML_DOCS }}
#      - name: Running the Sphinx to gh-pages Action
#        uses: uibcdf/action-sphinx-docs-to-gh-pages@v1.0.0
#        with:
#          branch: main
#          dir_docs: docs/source
#          sphinxapiopts: '--separate -f -E --implicit-namespaces -l -o . ../'
#          sphinxapiexclude: '../*setup* ../*.ipynb'
#          sphinxopts: ''
