name: Build, Test, & Deploy Wheel
env:
  CLONE_PATH: ${{ github.workspace }}
on:
  pull_request:
    branches: [main]
  # Limit to only branches named release_v*.*?
#  release:
#    types: [published]

jobs:
  build_distributions: 
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup base Python environment
        run: |
          $CLONE_PATH/.github/workflows/setup_base_python.sh ${{ runner.os }}
      - name: Run tests through wheels
        run: |
          python -m pip install build
          pushd $CLONE_PATH
          python -m build
          ls -lart ./dist
          popd
      - name: Archive wheel for later publishing
        uses: actions/upload-artifact@v4
        with:
          name: Taweret-distributions
          path: |
            ${{ env.CLONE_PATH }}/dist/taweret-*.tar.gz
            ${{ env.CLONE_PATH }}/dist/Taweret-*-py3-none-any.whl
