name: Taweret test and deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup pyhton 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
     - name: Install OpenMPI 
         run: |
          wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz
          tar -xvf ./openmpi-4.0.2.tar.gz
          ./openmpi-4.0.2/configure --prefix="/home/${USER}/.openmpi"
          make -j
          make install
          export PATH=${PATH}:/home/${USER}/.openmpi/bin/
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/${USER}/.openmpi/lib/
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run pytests
        run: |
          cd test/
          pytest .

  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    environment:
      name: pypi
      url: https://pypi.org/p/Taweret
    permission:
      permissions:
        id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup pyhton
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install -e .
      - name: Update directory structure 
        run: |
          mv Taweret src
      - name: Update pyproject.toml
        run: |
          git checkout testpypi -- pyproject.toml
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pyga/gh-action-pypi-publish@v1
